---
#=============== Common playbook for Linux Debian10 ===================#
# Created by Ivo Rodrigues Vieira
# On May 19, 2020
# Used in Debian 10.4
# Ansible version 2.9.7
# AWX version 11.2.0
#======================================================================#

 
# --- General --- Change the format  and the size of the history ----- #
- name: Change /etc/profile
  lineinfile: dest=/etc/profile line={{ item }}
  with_items:
    - '#--- Default export & Alias ---#'
    - 'export HISTTIMEFORMAT="%d/%m/%Y - %H:%M:%S - "'
    - 'export HISTSIZE="5000"'
    - 'export HISTFILESIZE="5000"'

#--- Manage users --- Add user support and add to the wheel group (sudo permission).  #
# In bash run 'openssl passwd -1' and the password. Copy the hash and paste in password: #
- name: Add user support
  user:
    name: support
    comment: "Support General"
    group: wheel
    shell: /bin/bash
    home: /home/support
    password: "oq2bYX5CL3nUCBY3."
    
#--- Timezone Settings --- Change the timezone#

- name: Configuring localtime
  file: src=/usr/share/zoneinfo/America/Toronto dest=/etc/localtime state=link force=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

#--- SSH Service --- Change ssh options#
- name: Setting basic SSH options
  lineinfile:
    dest=/etc/ssh/sshd_config
    state=present
    regexp={{ item.regexp }}
    line={{ item.line }}
  with_items:
    - { regexp: '#Port 22', line: 'Port 2222' } # Change from port 22 to 2222
    - { regexp: '#PermitRootLogin yes', line: 'PermitRootLogin yes' } # Allow root login via ssh
    - { regexp: '#Banner none', line: 'Banner /etc/ssh/banner_ssh' } # Add a banner
    - { regexp: '#ClientAliveInterval 0', line: 'ClientAliveInterval 120' } # Drop the inactive ssh session after the estimated time
    - { regexp: 'X11Forwarding yes', line: 'X11Forwarding no' } # Disable X11Forwarding

#--- SSH Protocol --- Force the use of protocol 2#
- name: Active Protocol 2 to SSH 
  lineinfile:
      dest=/etc/ssh/sshd_config
      line='Protocol 2'

#--- SSH User --- Add allowed users#      
- name: Setting Allow Users to access (SSH)
  lineinfile:
     dest=/etc/ssh/sshd_config
     line='AllowUsers support root'

#--- MOTD --- Change and add the motd template to the target. Template in roles/common_debian/templates/main.yml # 
- name: Add Motd
  template: src=motd dest=/etc/motd force=yes owner=root group=root mode=0755

#--- Banner SSH --- Change and add the banner file to the target. File in roles/common_debian/files/main.yml # 
# After changing the banner, restart the ssh service. Service restart parameters on roles/common_debian/handlers/main.yml.
- name: Add SSH Banner
  copy: src=banner_ssh dest=/etc/ssh/banner_ssh
  notify:
    - Restart SSH

#--- Packages Manager Debian ---#

- name: SISOP | Copy sources.list
  copy: src=sources.list dest=/etc/apt/sources.list
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: SISOP | Update system
  apt: update_cache=yes upgrade=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: SISOP | Running dist-upgrade
  apt: upgrade=dist
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

# Install packages that are in roles/common_debian/defaults/main.yml
- name: SISOP | Install packages
  apt: name={{common_packages_debian}} state=latest install_recommends=yes update_cache=yes
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
...